'use strict';
const $=id=>document.getElementById(id), store=QueenDemo;
// Presenter mode mirrors the customer page: ?mode=pitch hides demo scaffolding and keeps the preview link in the same mode.
const pitchMode=new URLSearchParams(location.search).get('mode')==='pitch';document.documentElement.dataset.mode=pitchMode?'pitch':'demo';if(pitchMode){const preview=document.querySelector('.admin-header a[href="index.html"]');if(preview)preview.href='index.html?mode=pitch';document.title=QueenI18n.t('Queen Spa · Merchant workspace');$('filter-search').placeholder=QueenI18n.t('ID or guest name');}
let selected=null, confirmAction=null, previousFocus=null, contentDirty=false, serviceDirty=false;
const photoChoices=['assets/queen-massage-room.webp','assets/queen-interior.webp','assets/queen-treatment-room.webp','assets/natural-oil.webp','assets/bamboo-lotion.webp','assets/hot-stone.webp'];
const photoDraft={};
let contentEditLocale=QueenI18n.locale,serviceEditLocale=QueenI18n.locale;
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
let noticeTimer=null;function notice(text){$('notice').textContent=text;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>{if($('notice').textContent===text)$('notice').textContent='';},3000);}
function showView(key){window.scrollTo({top:0,behavior:'instant'});document.querySelectorAll('[id^="view-"]').forEach(n=>n.hidden=n.id!=='view-'+key);document.querySelectorAll('[data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view===key));}
document.querySelectorAll('[data-view]').forEach(n=>n.onclick=()=>showView(n.dataset.view));
$('filter-range').value='upcoming';['filter-range','filter-date','filter-status','filter-search'].forEach(id=>$(id).addEventListener('input',renderBookings));$('clear-filters').onclick=()=>{['filter-date','filter-status','filter-search'].forEach(id=>$(id).value='');$('filter-range').value='upcoming';renderBookings();};
function renderBookings(){const state=store.read(),day=store.today(),today=state.bookings.filter(b=>b.date===day),active=today.filter(b=>b.status!=='cancelled');$('today-label').textContent=day;$('metrics').replaceChildren();[['Bookings',today.length,'All statuses today'],['Awaiting review',today.filter(b=>b.status==='pending').length,'Pending today'],['Guests',active.reduce((n,b)=>n+b.guests,0),'Excludes cancelled'],['Treatment value',store.money(active.reduce((n,b)=>n+b.unitPrice*b.guests,0)),'Estimate · not recognized revenue']].forEach(([label,val,note])=>{const box=el('div',undefined,'metric');box.append(el('span',label),el('strong',val),el('small',note));$('metrics').append(box);});const range=$('filter-range').value,dateFilter=$('filter-date').value;const inRange=b=>dateFilter?b.date===dateFilter:range==='today'?b.date===day:range==='upcoming'?b.date>=day:true;const rows=state.bookings.filter(b=>inRange(b)&&(!$('filter-status').value||b.status===$('filter-status').value)&&((b.id+' '+b.name).toLowerCase().includes($('filter-search').value.toLowerCase()))).sort((a,b)=>Number(b.status==='pending')-Number(a.status==='pending')||(a.status==='pending'&&b.status==='pending'?String(b.createdAt).localeCompare(String(a.createdAt)):0)||(a.date+a.time).localeCompare(b.date+b.time));$('result-count').textContent=rows.length+' bookings';$('booking-list').replaceChildren();if(!rows.length)$('booking-list').append(el('p',pitchMode?'No bookings match. Clear filters or wait for a new request.':'No bookings match. Clear filters, create a customer demo booking or reset sample data in Demo tools.','empty'));rows.forEach(b=>{const row=el('button',undefined,'booking-row');row.type='button';row.setAttribute('aria-label','Open '+b.id+' '+b.name);row.dataset.bookingId=b.id;const guest=el('span');const guestName=el('strong',b.name);guestName.dataset.userContent='';guest.append(guestName,el('small',b.id));const treatment=el('span');treatment.append(el('strong',b.serviceName),el('small',b.duration+' min · '+b.guests+' '+(b.guests===1?'guest':'guests')));const time=el('span');time.append(el('strong',b.time),el('small',b.date));row.append(guest,treatment,time,el('span',b.status,'status '+b.status),el('span','↗'));row.onclick=()=>openDetail(b.id);$('booking-list').append(row);});$('store-error').textContent=store.problem;renderBadge(state,day);detectNewRequests(state);if(selected&&$('detail').open)renderDetail();}
// Pending requests from today onward stay visible in the sidebar whichever view is open.
function renderBadge(state,day){const badge=$('pending-badge');const n=state.bookings.filter(b=>b.status==='pending'&&b.date>=day).length;badge.textContent=n?String(n):'';badge.hidden=!n;$('pending-badge-label').hidden=!n;}
// A customer request arriving from another tab announces itself; clicking it jumps to the row.
let knownIds=null,toastTimer=null;
function detectNewRequests(state){const ids=new Set(state.bookings.map(b=>b.id));if(knownIds){const fresh=state.bookings.filter(b=>b.source==='customer'&&!knownIds.has(b.id));if(fresh.length)announce(fresh[0]);}knownIds=ids;}
function hideToast(){$('new-request')?.remove();clearTimeout(toastTimer);}
function announce(b){hideToast();const toast=el('div',undefined,'toast');toast.id='new-request';toast.setAttribute('role','status');$('store-error').after(toast);const button=el('button','New request · '+b.id+' · '+b.date+' '+b.time+' · '+b.serviceName);button.type='button';button.onclick=()=>{hideToast();showView('bookings');if(!document.querySelector('[data-booking-id="'+b.id+'"]')){$('filter-range').value='all';['filter-date','filter-status','filter-search'].forEach(id=>$(id).value='');renderBookings();}const row=document.querySelector('[data-booking-id="'+b.id+'"]');if(row){row.scrollIntoView({block:'center'});row.focus({preventScroll:true});row.classList.add('is-new');setTimeout(()=>row.classList.remove('is-new'),1600);}};toast.append(button);toastTimer=setTimeout(hideToast,4000);}
function openDetail(id){selected=id;previousFocus=document.activeElement;renderDetail();$('detail').showModal();$('detail-title').focus();}
function closeDetail(){$('detail').close();previousFocus?.focus();selected=null;}
$('close-detail').onclick=closeDetail;$('detail').addEventListener('cancel',e=>{e.preventDefault();closeDetail();});
function renderDetail(){const b=store.read().bookings.find(b=>b.id===selected);if(!b){closeDetail();return;}$('detail-title').textContent=b.id;$('detail-content').replaceChildren();const grid=el('div',undefined,'detail-grid');[[pitchMode?'Guest':'Fictional guest',b.name+' · '+b.email],['Status',null],['Ritual',b.serviceName+' · '+b.duration+' min'],['Party',b.guests+' '+(b.guests===1?'guest':'guests')],['Preferred time',b.date+' · '+b.time+' GMT+7'],['Original treatment subtotal',store.money(b.unitPrice*b.guests)]].forEach(([label,value])=>{const p=el('p');const text=value===null?el('span',b.status,'status '+b.status):el('span',value);if(label==='Fictional guest'||label==='Guest')text.dataset.userContent='';p.append(el('small',label),text);grid.append(p);});$('detail-content').append(grid);$('new-date').value=b.date;$('new-date').min=store.today();$('new-time').value=b.time;const terminal=['completed','cancelled'].includes(b.status);$('reschedule-form').hidden=terminal;$('detail-actions').replaceChildren();if(!terminal){if(b.status!=='confirmed')addAction('Confirm booking','confirmed');if(['confirmed','rescheduled'].includes(b.status))addAction('Mark completed','completed');addAction('Cancel booking','cancelled');}$('history').replaceChildren(...b.history.map(h=>el('li',new Date(h.at).toLocaleString(QueenI18n.tag,{timeZone:'Asia/Ho_Chi_Minh'})+' GMT+7 — '+h.text)));}
function addAction(label,status){const button=el('button',label,status==='confirmed'?'button':'secondary-button');button.onclick=()=>{if(status==='cancelled')ask(pitchMode?'Cancel this booking?':'Cancel this demo booking?',pitchMode?'The guest will see cancelled. No notification is sent.':'The customer demo view will show cancelled. No notification is sent.',()=>changeStatus(status));else changeStatus(status);};$('detail-actions').append(button);}
function changeStatus(status,date,time){try{store.save(s=>{const b=s.bookings.find(b=>b.id===selected);if(!b||['cancelled','completed'].includes(b.status))throw Error('This booking is no longer editable.');if(status==='completed'&&!['confirmed','rescheduled'].includes(b.status))throw Error('Confirm the booking before completing it.');b.status=status;if(date){b.date=date;b.time=time;}b.history.push({at:new Date().toISOString(),text:(pitchMode?'Status changed to ':'Demo admin changed status to ')+status+(date?' · '+date+' '+time:'')+'. No notification sent.'});});$('detail-error').textContent='';notice(pitchMode?'Booking updated.':'Demo booking updated.');}catch(e){$('detail-error').textContent=e.message;}}
$('reschedule-form').onsubmit=e=>{e.preventDefault();const date=$('new-date'),time=$('new-time');if(!date.value||date.value<store.today()||!date.validity.valid||!time.value||!time.validity.valid){$('detail-error').textContent='Choose today or later and a valid 15-minute time.';return;}changeStatus('rescheduled',date.value,time.value);};
function ask(title,copy,action){confirmAction=action;$('confirm-title').textContent=title;$('confirm-copy').textContent=copy;$('confirm-dialog').showModal();$('confirm-title').focus();}
$('confirm-no').onclick=()=>{$('confirm-dialog').close();confirmAction=null;};$('confirm-yes').onclick=()=>{$('confirm-dialog').close();const action=confirmAction;confirmAction=null;action?.();};
['samples','empty'].forEach(key=>$('reset-'+key).onclick=()=>ask('Reset the entire demo?','This removes all saved bookings, uploaded photos and menu/content edits. '+(key==='samples'?'Six fictional sample bookings will be loaded.':'The booking list will be empty.'),()=>{try{store.reset(key==='samples');loadContent();loadService();notice('Demo reset. Both views now use the restored data.');}catch(e){$('store-error').textContent=e.message;}}));
async function readPhoto(file){if(!file||!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024)throw Error('Choose a PNG, JPEG or WebP photo under 2 MB.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const data=canvas.toDataURL('image/webp',.78);if(data.length>500000)throw Error('This photo is too complex for local demo storage. Choose a smaller image.');return data;}
function photoEditor(key,value,parent,changed){photoDraft[key]=value;const box=el('div',undefined,'photo-editor');const image=el('img');image.src=value;image.alt='Photo preview · '+key;const label=el('label','Choose a Queen photo');const select=el('select');photoChoices.forEach((path,i)=>select.append(QueenI18n.option(['Treatment room','Interior','Second room','Natural oil','Bamboo','Hot stone'][i],path)));if(value.startsWith('data:'))select.prepend(QueenI18n.option('Uploaded photo',value));select.value=value;select.onchange=()=>{image.src=select.value;photoDraft[key]=select.value;changed();};label.append(select);const uploadLabel=el('label','Or upload your own photo');const input=el('input');input.type='file';input.accept='image/png,image/jpeg,image/webp';input.setAttribute('aria-label','Upload '+key+' photo');const error=el('p');error.setAttribute('role','alert');input.onchange=async()=>{try{const data=await readPhoto(input.files[0]);photoDraft[key]=data;image.src=data;changed();error.textContent='Ready to save. Photo is stored only in this browser.';}catch(e){error.textContent=e.message;}};input.className='upload-input';const choose=el('button','Choose image','secondary-button');choose.type='button';choose.onclick=()=>input.click();const filename=el('span','No image selected','upload-filename');input.addEventListener('change',()=>{const file=input.files[0];filename.toggleAttribute('data-user-content',Boolean(file));filename.textContent=file?.name||'No image selected';});uploadLabel.append(input,choose,filename);box.append(image,label,uploadLabel,error,el('p','Max 2 MB. Optimized locally. Use only photos you may reuse.'));parent.append(box);}
function loadContent(){const c=store.read().content;contentEditLocale=QueenI18n.locale;$('content-language-note').textContent='Content language: '+(contentEditLocale==='vi'?'Vietnamese':'English');const copy=c.localeCopies?.[contentEditLocale]||c;['title','intro','address','hours'].forEach(key=>$('content-'+key).value=String(copy[key]).split('\n').map(QueenI18n.t).join('\n'));const contact=c.contact||{};$('content-phone').value=contact.phone||'';$('content-whatsapp').value=contact.whatsapp||'';$('content-zalo').value=contact.zalo||'';$('content-mapsurl').value=contact.mapsUrl||'';$('content-photos').replaceChildren();['heroImage','galleryOne','galleryTwo'].forEach(key=>photoEditor(key,c[key],$('content-photos'),()=>contentDirty=true));contentDirty=false;}
$('content-form').oninput=()=>contentDirty=true;$('discard-content').onclick=()=>{loadContent();$('content-error').textContent='';};$('content-form').onsubmit=e=>{e.preventDefault();try{const copy={};['title','intro','address','hours'].forEach(key=>{copy[key]=$('content-'+key).value.trim();if(!copy[key])throw Error('All copy fields are required.');});['heroImage','galleryOne','galleryTwo'].forEach(key=>copy[key]=photoDraft[key]);const contact={phone:$('content-phone').value.trim(),whatsapp:$('content-whatsapp').value.trim(),zalo:$('content-zalo').value.trim(),mapsUrl:$('content-mapsurl').value.trim()};for(const key of ['phone','whatsapp','zalo']){const v=contact[key],digits=v.replace(/\D/g,'');if(v&&(!/^[+\d()\s.\-]+$/.test(v)||digits.length<7||digits.length>15))throw Error('Use a phone number with 7–15 digits, including your country code.');}if(contact.mapsUrl&&!/^https:\/\/\S+$/.test(contact.mapsUrl))throw Error('Use a valid https:// link.');store.save(s=>{s.content.localeCopies??={};s.content.localeCopies[contentEditLocale]=Object.fromEntries(['title','intro','address','hours'].map(k=>[k,copy[k]]));if(contentEditLocale==='en')Object.assign(s.content,s.content.localeCopies.en);['heroImage','galleryOne','galleryTwo'].forEach(k=>s.content[k]=copy[k]);s.content.contact=contact;});contentDirty=false;$('content-error').textContent='';notice('Website changes saved. Check the customer preview.');}catch(e){$('content-error').textContent=e.message;}};
function optionRow(minutes='',price=''){const row=el('div',undefined,'option-row');[['Minutes',minutes,'minutes',15,240],['Price · VND',price,'price',10000,10000000]].forEach(([label,value,key,min,max])=>{const wrap=el('label',label);const input=el('input');input.type='number';input.required=true;input.min=min;input.max=max;input.step=1;input.value=value;input.dataset.option=key;wrap.append(input);row.append(wrap);});const remove=el('button','Remove','secondary-button');remove.type='button';remove.onclick=()=>{if($('option-rows').children.length===1){$('service-error').textContent='Keep at least one duration.';return;}row.remove();serviceDirty=true;};row.append(remove);$('option-rows').append(row);}
function loadService(){const s=store.read().services[$('service-key').value];serviceEditLocale=QueenI18n.locale;$('service-language-note').textContent='Content language: '+(serviceEditLocale==='vi'?'Vietnamese':'English');const copy=s.localeCopies?.[serviceEditLocale]||s;$('service-name').value=QueenI18n.t(copy.name);$('service-description').value=QueenI18n.t(copy.description);$('option-rows').replaceChildren();s.options.forEach(p=>optionRow(...p));$('service-photo').replaceChildren();photoEditor('serviceImage',s.image,$('service-photo'),()=>serviceDirty=true);serviceDirty=false;}
$('service-key').onchange=loadService;$('discard-service').onclick=()=>{loadService();$('service-error').textContent='';};$('add-option').onclick=()=>{if($('option-rows').children.length>=5){$('service-error').textContent='Maximum five durations.';return;}optionRow();serviceDirty=true;};$('service-form').oninput=()=>serviceDirty=true;$('service-form').onsubmit=e=>{e.preventDefault();try{const options=[...$('option-rows').children].map(row=>['minutes','price'].map(key=>Number(row.querySelector('[data-option="'+key+'"]').value)));if(options.some(([m,p])=>!Number.isInteger(m)||m<15||m>240||!Number.isInteger(p)||p<10000||p>10000000)||new Set(options.map(p=>p[0])).size!==options.length)throw Error('Use unique whole-minute durations and valid whole VND prices.');const name=$('service-name').value.trim(),description=$('service-description').value.trim();if(!name||!description)throw Error('Name and description are required.');store.save(s=>{const service=s.services[$('service-key').value];service.localeCopies??={};service.localeCopies[serviceEditLocale]={name,description};if(serviceEditLocale==='en')Object.assign(service,{name,description});Object.assign(service,{options:options.sort((a,b)=>a[0]-b[0]),image:photoDraft.serviceImage});});serviceDirty=false;$('service-error').textContent='';notice('Treatment saved. Existing bookings retain their original price.');}catch(e){$('service-error').textContent=e.message;}};
document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const nodes=[...dialog.querySelectorAll('button,input,select,a[href]')].filter(n=>!n.disabled&&n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&(document.activeElement===first||!nodes.includes(document.activeElement))){e.preventDefault();last?.focus();}else if(!e.shiftKey&&(document.activeElement===last||!nodes.includes(document.activeElement))){e.preventDefault();first?.focus();}}));
store.subscribe(()=>{renderBookings();if(!contentDirty)loadContent();if(!serviceDirty)loadService();});renderBookings();loadContent();loadService();

document.addEventListener('queen-locale-change',()=>{if(!contentDirty)loadContent();if(!serviceDirty)loadService();if(selected&&$('detail').open){const b=store.read().bookings.find(b=>b.id===selected);if(b)$('history').replaceChildren(...b.history.map(h=>el('li',new Date(h.at).toLocaleString(QueenI18n.tag,{timeZone:'Asia/Ho_Chi_Minh'})+' GMT+7 — '+h.text)));}});
